services:
  web:
    build: .
    container_name: htmx-chub
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # command: '/bin/sh -c "while : ; do sleep 1 ; done ;"'
    command: '/bin/sh -c "sleep 5; uv run manage.py runserver 0.0.0.0:8000"'
