# Generated by Django 5.2.7 on 2025-10-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SerializeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(db_index=True, max_length=255)),
                ('configuration_id', models.IntegerField()),
                ('process_step_num', models.IntegerField()),
                ('job_number', models.CharField(db_index=True, max_length=255)),
                ('start_operator', models.CharField(db_index=True, max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_operator', models.CharField(db_index=True, max_length=255)),
                ('end_datetime', models.DateTimeField()),
                ('notes', models.CharField(db_index=True, max_length=255)),
                ('scrapped', models.CharField(db_index=True, max_length=255)),
                ('created_by', models.CharField(db_index=True, max_length=255)),
                ('created_datetime', models.DateTimeField()),
                ('modified_by', models.CharField(db_index=True, max_length=255)),
                ('modified_datetime', models.DateTimeField()),
            ],
        ),
    ]
