# Generated by Django 5.2.7 on 2025-10-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serializemaster',
            name='created_by',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='serializemaster',
            name='end_operator',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='serializemaster',
            name='job_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='serializemaster',
            name='modified_by',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='serializemaster',
            name='notes',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='serializemaster',
            name='part_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='serializemaster',
            name='scrapped',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='serializemaster',
            name='start_operator',
            field=models.CharField(max_length=255),
        ),
    ]
