# Generated by Django 5.2.7 on 2025-10-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialize', '0002_alter_serializemaster_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serializemaster',
            name='created_datetime',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='serializemaster',
            name='end_datetime',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='serializemaster',
            name='modified_datetime',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='serializemaster',
            name='start_datetime',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
